AWSTemplateFormatVersion: "2010-09-09"

Resources: 
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nycgroup05datalake-2

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nycgroup05datawarehouse-2

  IngestionGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: nyc-ingestion-2
      Role: arn:aws:iam::314119374691:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 5
      Timeout: 120
      WorkerType: G.1X
      Command:
        Name: glueetl-2
        ScriptLocation: s3://nycgroup05datalake-2/scripts/injesion.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  TransformationGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: nyc-transformation-2
      Role: arn:aws:iam::314119374691:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 5
      Timeout: 240
      WorkerType: G.1X
      Command:
        Name: glueetl-22
        ScriptLocation: s3://nycgroup05datalake-2/scripts/transformation.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1

  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: nyc-workflow-2

  GlueTriggerImport:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - IngestionGlueJob
    Properties:
      Actions:
        - JobName: !Ref IngestionGlueJob
      Description: Triggers the Import Jobs
      Name: gluetriggerimport-2
      Type: EVENT
      WorkflowName: nyc-workflow-2

  GlueTriggerTransform:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - TransformationGlueJob
      - GlueTriggerImport
    Properties:
      Actions:
        - JobName: !Ref TransformationGlueJob
      Description: Triggers the transformation job
      Name: gluetriggertransform-2
      Predicate:
        Conditions:
          - JobName: !Ref IngestionGlueJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
        Logical: AND
      Type: CONDITIONAL
      StartOnCreation: True
      WorkflowName: nyc-workflow-2

  GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: gitdatabase-2

  DataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - SourceBucket
      - DestinationBucket
      - GlueDatabase
      - GlueWorkflow
      - GlueTriggerTransform
    Properties:
      Name: data-crawler5-2
      DatabaseName: gitdatabase-2
      Targets:
        S3Targets:
          - Path: s3://nycgroup05datawarehouse-2/warehousenyc/ 
      Role: arn:aws:iam::314119374691:role/LabRole

  GlueTriggerForCrawler:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueTriggerTransform
    Properties:
      Name: GlueTriggerForCrawler-2
      Type: CONDITIONAL
      Actions:
        - CrawlerName: !Ref DataCrawler
          NotificationProperty:
            NotifyDelayAfter: 1
      Predicate:
        Conditions:
          - JobName: !Ref TransformationGlueJob
            LogicalOperator: EQUALS
            State: SUCCEEDED
        Logical: AND
      Type: CONDITIONAL
      StartOnCreation: True
      WorkflowName: nyc-workflow-2


  MyAthenaWorkGroup:
      Type: AWS::Athena::WorkGroup
      Properties:
          Name: gitworkgrp-2
          Description: workgroup for Athena
          State: ENABLED
          WorkGroupConfiguration:
              BytesScannedCutoffPerQuery: 200000000
              EnforceWorkGroupConfiguration: false
              PublishCloudWatchMetricsEnabled: true
              RequesterPaysEnabled: true
              ResultConfiguration:
                  OutputLocation: s3://nycgroup05datawarehouse-2/Query/    
